eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id: product-service
          uri:
            lb://PRODUCT-SERVICE
          #        uri: http://localhost:8081
          predicates:
            - Path=/product-service/**
        - id: order-service
          uri:
            lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**